name: hw-dev
services:
  downloader:
    build:
      dockerfile: Dockerfile.downloader
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./.build/dev/downloads:/.build/dev/downloads

  browser:
    image: ghcr.io/ra341/chromtrol:latest
    container_name: browser
    security_opt:
      # Prevents Chromium from crashing in Docker
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
    #      - CHROME_CLI=--remote-debugging-port=9222 --remote-debugging-address=0.0.0.0
    ports:
      - "8998:8080" # control plane
      - "3012:3000" # Web UI
    #      - "9222:9222"
    volumes:
      # This volume holds the browser profile and SQLite databases
      - ./downloader/downloader/browser_data:/config
