FROM ghcr.io/ra341/dfw:latest AS ui

WORKDIR /build

COPY frontend/pubspec.lock frontend/pubspec.yaml ./

RUN flutter pub get

COPY frontend .

RUN flutter build web --wasm

FROM golang:1-trixie AS builder

WORKDIR /app

COPY core/go.mod core/go.sum ./

RUN go mod download

COPY core .

RUN CGO=1 go build -ldflags "-s -w" -o homework "./cmd/homework"

FROM gcr.io/distroless/base-debian13:nonroot

WORKDIR /app

COPY --from=builder /app/homework homework
COPY --from=ui /build/build/web web

ENTRYPOINT ["./homework"]
