FROM python:3.14-slim-trixie AS scipt-exec

WORKDIR /build

COPY core/downloader/entrypoint.sh entrypoint.sh

RUN chmod +x entrypoint.sh

FROM golang:1-trixie AS builder

WORKDIR /app

COPY core/go.mod core/go.sum ./

RUN go mod download

COPY core .

RUN CGO=0 go build -ldflags "-s -w" -o hwdownloader "./cmd/downloader"

FROM python:3.14-slim-trixie AS backend

RUN apt-get update && apt-get install -y \
    ffmpeg \
    curl \
    unzip \
    gosu \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install -U "yt-dlp[default,curl-cffi]"

# Install deno, uv, and ffmpeg globally for use by non-root users
COPY --from=denoland/deno:latest /usr/bin/deno /usr/bin/deno

RUN deno --version
RUN ffmpeg -version
RUN ffprobe -version

COPY --from=builder /app/hwdownloader /usr/bin/hwdownloader

WORKDIR /app

COPY --from=scipt-exec /build/entrypoint.sh entrypoint.sh

CMD ["./entrypoint.sh"]
