FROM base-gomod AS builder

WORKDIR /app

COPY core .

RUN CGO_ENABLED=0 go build -ldflags "-s -w" -o hwd "./cmd/scribe"

FROM base-yt

WORKDIR /app

COPY --from=builder /app/hwd /usr/bin/hwd

COPY docker/entrypoint.sh entrypoint.sh

ENTRYPOINT ["./entrypoint.sh", "hwd"]
