// Code generated by "enumer -type=Role -json -text -output gen_enum_role.go"; DO NOT EDIT.

package asset

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _RoleName = "MainThumbnailBackdropTrailerPoster"

var _RoleIndex = [...]uint8{0, 4, 13, 21, 28, 34}

const _RoleLowerName = "mainthumbnailbackdroptrailerposter"

func (i Role) String() string {
	if i < 0 || i >= Role(len(_RoleIndex)-1) {
		return fmt.Sprintf("Role(%d)", i)
	}
	return _RoleName[_RoleIndex[i]:_RoleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RoleNoOp() {
	var x [1]struct{}
	_ = x[Main-(0)]
	_ = x[Thumbnail-(1)]
	_ = x[Backdrop-(2)]
	_ = x[Trailer-(3)]
	_ = x[Poster-(4)]
}

var _RoleValues = []Role{Main, Thumbnail, Backdrop, Trailer, Poster}

var _RoleNameToValueMap = map[string]Role{
	_RoleName[0:4]:        Main,
	_RoleLowerName[0:4]:   Main,
	_RoleName[4:13]:       Thumbnail,
	_RoleLowerName[4:13]:  Thumbnail,
	_RoleName[13:21]:      Backdrop,
	_RoleLowerName[13:21]: Backdrop,
	_RoleName[21:28]:      Trailer,
	_RoleLowerName[21:28]: Trailer,
	_RoleName[28:34]:      Poster,
	_RoleLowerName[28:34]: Poster,
}

var _RoleNames = []string{
	_RoleName[0:4],
	_RoleName[4:13],
	_RoleName[13:21],
	_RoleName[21:28],
	_RoleName[28:34],
}

// RoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RoleString(s string) (Role, error) {
	if val, ok := _RoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Role values", s)
}

// RoleValues returns all values of the enum
func RoleValues() []Role {
	return _RoleValues
}

// RoleStrings returns a slice of all String values of the enum
func RoleStrings() []string {
	strs := make([]string, len(_RoleNames))
	copy(strs, _RoleNames)
	return strs
}

// IsARole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Role) IsARole() bool {
	for _, v := range _RoleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Role
func (i Role) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Role
func (i *Role) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Role should be a string, got %s", data)
	}

	var err error
	*i, err = RoleString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Role
func (i Role) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Role
func (i *Role) UnmarshalText(text []byte) error {
	var err error
	*i, err = RoleString(string(text))
	return err
}
