// Code generated by "enumer -type=Type -json -text -output gen_enum_type.go"; DO NOT EDIT.

package asset

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _TypeName = "UnknownVideoImageSubtitleAudio"

var _TypeIndex = [...]uint8{0, 7, 12, 17, 25, 30}

const _TypeLowerName = "unknownvideoimagesubtitleaudio"

func (i Type) String() string {
	if i < 0 || i >= Type(len(_TypeIndex)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _TypeName[_TypeIndex[i]:_TypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TypeNoOp() {
	var x [1]struct{}
	_ = x[Unknown-(0)]
	_ = x[Video-(1)]
	_ = x[Image-(2)]
	_ = x[Subtitle-(3)]
	_ = x[Audio-(4)]
}

var _TypeValues = []Type{Unknown, Video, Image, Subtitle, Audio}

var _TypeNameToValueMap = map[string]Type{
	_TypeName[0:7]:        Unknown,
	_TypeLowerName[0:7]:   Unknown,
	_TypeName[7:12]:       Video,
	_TypeLowerName[7:12]:  Video,
	_TypeName[12:17]:      Image,
	_TypeLowerName[12:17]: Image,
	_TypeName[17:25]:      Subtitle,
	_TypeLowerName[17:25]: Subtitle,
	_TypeName[25:30]:      Audio,
	_TypeLowerName[25:30]: Audio,
}

var _TypeNames = []string{
	_TypeName[0:7],
	_TypeName[7:12],
	_TypeName[12:17],
	_TypeName[17:25],
	_TypeName[25:30],
}

// TypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TypeString(s string) (Type, error) {
	if val, ok := _TypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Type values", s)
}

// TypeValues returns all values of the enum
func TypeValues() []Type {
	return _TypeValues
}

// TypeStrings returns a slice of all String values of the enum
func TypeStrings() []string {
	strs := make([]string, len(_TypeNames))
	copy(strs, _TypeNames)
	return strs
}

// IsAType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Type) IsAType() bool {
	for _, v := range _TypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Type
func (i Type) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Type
func (i *Type) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Type should be a string, got %s", data)
	}

	var err error
	*i, err = TypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Type
func (i Type) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Type
func (i *Type) UnmarshalText(text []byte) error {
	var err error
	*i, err = TypeString(string(text))
	return err
}
